baseurl: https://modus.trimble.com/
title: Trimble Modus Design System
languageCode: en-US
locale: en-US

enableInlineShortcodes: true
enableGitInfo: true
googleAnalytics: "UA-787590-52"

params:
  title: Trimble Modus Design System
  modusVersion: "1.2"
  modusBootstrapVersion: "1.2.0"
  modusIconsVersion: "0.5.1"
  author: "Trimble"
  copyrightHolder: "Trimble Inc."
  images:
    - https://modus.trimble.com/img/preview.png

publishdir: "./build/"

disableKinds: ["taxonomy", "taxonomyTerm", "404"]

pygmentsUseClasses: true

outputs:
  home: ["HTML", "JSON"]

privacy:
  googleAnalytics:
    anonymizeIP: true
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true

menu:
  main:
    - name: Start
      url: "/start/"
      weight: 1
    - name: Foundations
      url: "/foundations/"
      weight: 2
    - name: Components
      url: "/components/"
      weight: 3
    - Name: Community
      url: "/community/"
      weight: 4

  start:
    - name: Designers
      url: "/designers/"
      weight: 1
    - name: Developers
      url: "/developers/"
      weight: 2
    - name: Device Support
      url: "/device-support/"
      weight: 3
    - name: Status
      url: "/status/"
      weight: 4

  foundations:
    - name: Logo Usage
      url: /foundations/logo-usage/
      weight: 1
    - name: Writing Style
      url: /foundations/writing-style/
      weight: 2
    - name: Typography
      url: /foundations/typography/
      weight: 3
    - name: Color Palette
      url: /foundations/color-palette/
      weight: 4
    - name: Icon Definitions
      url: /foundations/icon-definitions/
      weight: 5
    - name: Accessibility
      url: /foundations/accessibility/
      weight: 6
    - name: Grid & Spacing
      url: /foundations/grid-and-spacing/
      weight: 7
    - name: Shadows & Depth
      url: /foundations/shadows-and-depth/
      weight: 8
    - name: Data Visualization
      url: /foundations/data-vis/
      weight: 9

  components:
    - name: Accordions
      url: /components/accordions/
    - name: Alerts
      url: /components/alerts/
    - name: Badges
      url: /components/badges/
    - name: Breadcrumbs
      url: /components/breadcrumbs/
    - name: Buttons
      url: /components/buttons/
    - name: Cards
      url: /components/cards/
    - name: Chips
      url: /components/chips/
    - name: Checkboxes
      url: /components/checkboxes/
    - name: Dropdowns
      url: /components/dropdowns/
    - name: Inputs
      url: /components/inputs/
    - name: Lists
      url: /components/lists/
    - name: Messages
      url: /components/messages/
    - name: Modals
      url: /components/modals/
    - name: Navbar
      url: /components/navbar/
    - name: Pagination
      url: /components/pagination/
    - name: Progress Bars
      url: /components/progress-bars/
    - name: Radio Buttons
      url: /components/radio-buttons/
    - name: Sliders
      url: /components/sliders/
    - name: Spinners
      url: /components/spinners/
    - name: Switches
      url: /components/switches/
    - name: Tables
      url: /components/tables/
    - name: Tabs
      url: /components/tabs/
    - name: Toasts
      url: /components/toasts/
    - name: Tooltips
      url: /components/tooltips/
    - name: Transactional Emails
      url: /components/transactional-emails/

  resources:
    - name: "News & Articles"
      url: /news/
    - name: Community
      url: /community/
    - name: Contact
      url: /contact/

  community:
    - name: News & Articles
      url: /news/
      weight: 1
    - name: How to Contribute
      url: /community/contribute/
      weight: 2
    - name: Tiger Teams
      url: /community/tiger-teams/
      weight: 3
    - name: Contribution Process
      url: /community/contribution-process/
      weight: 4
    - name: Submission Guidelines
      url: /community/submission-guidelines/
      weight: 5
    - name: Modus Adoption
      url: /community/adoption/
      weight: 6
    - name: Contact Us
      url: /community/contact/
      weight: 7

module:
  mounts:
    - source: static
      target: static
    - source: assets/static/favicon.ico
      target: static/favicon.ico
    - source: assets/static/robots.txt
      target: static/robots.txt
    - source: node_modules/bootstrap/dist/js/bootstrap.bundle.min.js
      target: static/js/bootstrap.bundle.min.js
    - source: node_modules/bootstrap/dist/js/bootstrap.bundle.min.js.map
      target: static/js/bootstrap.bundle.min.js.map
    - source: node_modules/list.js/dist/list.min.js
      target: static/js/list.min.js
    - source: node_modules/list.js/dist/list.min.js.map
      target: static/js/list.min.js.map

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    codeFences: true
    style: monokai

# https://gohugo.io/getting-started/configuration/#configure-minify
minify:
  minifyOutput: true
  tdewolff:
    html:
      keepEndTags: false
      keepWhitespace: true
    xml:
      keepWhitespace: true
