baseurl: https://modus.trimble.com/
title: Trimble Modus Design System
languageCode: en-US
locale: en-US

enableInlineShortcodes: true
enableGitInfo: true
googleAnalytics: ""

params:
  title: Trimble Modus Design System
  modusVersion: "1.2"
  modusIconsVersion: "0.5.1"
  author: "Trimble"
  copyrightHolder: "Trimble Inc."
  images:
    - https://modus.trimble.com/img/preview.png

publishdir: "./build/"

disableKinds: ["taxonomy", "taxonomyTerm", "404"]

pygmentsUseClasses: true

outputs:
  home: ["HTML", "JSON"]

privacy:
  googleAnalytics:
    anonymizeIP: true
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true

menu:
  main:
    - name: Start
      url: "/start/"
      weight: 1
    - name: Foundations
      url: "/foundations/"
      weight: 2
    - name: Components
      id: Components
      url: "/components/web/"
      weight: 3
    - name: Web
      parent: Components
      url: "/components/web/"
      pre: "<img src='/img/icons/web.svg' width=28 height=28 class='icon' alt>"
      post: "React, Web Components, Angular<br>for web applications."
      weight: 1
    - name: In-Field
      parent: Components
      url: "/components/in-field/"
      pre: "<img src='/img/icons/in-field.svg' width=28 height=28 class='icon' alt>"
      post: "High-contrast library specific<br>to applications used outdoors."
      weight: 2
    - name: Mobile
      parent: Components
      url: "/components/mobile/"
      pre: "<img src='/img/icons/mobile.svg' width=28 height=28 class='icon' alt>"
      post: ""
      weight: 3
#   - name: XR
#     parent: Components
#     url: "/components/xr/"
#     pre: "<img src='/img/icons/xr.svg' width=28 height=28 class='icon' alt>"
#     post: ""
#     weight: 4

    - Name: Community
      url: "/community/"
      weight: 4

  start:
    - name: Designers
      url: "/designers/"
      weight: 1
    - name: Developers
      url: "/developers/"
      weight: 2
    - name: Device Support
      url: "/device-support/"
      weight: 3
    - name: Status
      url: "/status/"
      weight: 4

  foundations:
    - name: Accessibility
      url: /foundations/accessibility/
    - name: Color Palette
      url: /foundations/color-palette/
    - name: Dark Mode
      url: /foundations/dark-mode/
    - name: Data Visualization
      url: /foundations/data-vis/
    - name: Grid & Spacing
      url: /foundations/grid-and-spacing/
    - name: Icon Definitions
      url: /foundations/icon-definitions/
    - name: Logo Usage
      url: /foundations/logo-usage/
    - name: Modus 3D
      url: /foundations/modus-3d/
    - name: Shadows & Depth
      url: /foundations/shadows-and-depth/
    - name: Trimble ID (TID)
      url: /foundations/tid/
    - name: Typography
      url: /foundations/typography/
    - name: Voice & Tone
      url: /foundations/voice-and-tone/
    - name: Writing Style
      url: /foundations/writing-style/

  components_web:
    - name: Introduction
      url: /components/web/introduction/
      weight: 1
      post: "border-bottom"
    - name: Accordions
      url: /components/web/accordions/
    - name: Alerts
      url: /components/web/alerts/
    - name: Autocomplete
      url: /components/web/autocomplete/
    - name: Badges
      url: /components/web/badges/
    - name: Breadcrumbs
      url: /components/web/breadcrumbs/
    - name: Buttons
      url: /components/web/buttons/
    - name: Cards
      url: /components/web/cards/
    - name: Chips
      url: /components/web/chips/
    - name: Checkboxes
      url: /components/web/checkboxes/
    - name: Content Tree
      url: /components/web/content-tree/
    - name: Date & Time Picker
      url: /components/web/date-time-picker/
    - name: Dropdowns
      url: /components/web/dropdowns/
    - name: File Upload Dropzone
      url: /components/web/file-upload-dropzone/
    - name: Inputs
      url: /components/web/inputs/
    - name: Lists
      url: /components/web/lists/
    - name: Messages
      url: /components/web/messages/
    - name: Modals
      url: /components/web/modals/
    - name: Navbar
      url: /components/web/navbar/
    - name: Pagination
      url: /components/web/pagination/
    - name: Progress Bars
      url: /components/web/progress-bars/
    - name: Radio Buttons
      url: /components/web/radio-buttons/
    - name: Side Navigation
      url: /components/web/side-navigation/
    - name: Sliders
      url: /components/web/sliders/
    - name: Spinners
      url: /components/web/spinners/
    - name: Switches
      url: /components/web/switches/
    - name: Tables
      url: /components/web/tables/
    - name: Tabs
      url: /components/web/tabs/
    - name: Toasts
      url: /components/web/toasts/
    - name: Tooltips
      url: /components/web/tooltips/
    - name: Transactional Emails
      url: /components/web/transactional-emails/

  components_infield:
    - name: Introduction
      url: /components/in-field/introduction/
      weight: 1
      post: "border-bottom"
    - name: Accordions
      url: /components/in-field/accordions/
    - name: Alarms
      url: /components/in-field/alarms/
    - name: Badges
      url: /components/in-field/badges/
    - name: Buttons
      url: /components/in-field/buttons/
    - name: Cards
      url: /components/in-field/cards/
    - name: Checkboxes
      url: /components/in-field/checkboxes/
    - name: Chips
      url: /components/in-field/chips/
    - name: Dropdowns
      url: /components/in-field/dropdowns/
    - name: Inputs
      url: /components/in-field/inputs/
    - name: Lists
      url: /components/in-field/lists/
    - name: Messages
      url: /components/in-field/messages/
    - name: Modals
      url: /components/in-field/modals/
    - name: Navbar
      url: /components/in-field/navbar/
    - name: Notifications
      url: /components/in-field/notifications/
    - name: Prompts
      url: /components/in-field/prompts/
    - name: Radio Buttons
      url: /components/in-field/radio-buttons/
    - name: Segmented Controls
      url: /components/in-field/segmented-controls/
    - name: Sliders
      url: /components/in-field/sliders/
    - name: Switches
      url: /components/in-field/switches/
    - name: Tabs
      url: /components/in-field/tabs/

  components_mobile:
    - name: Introduction
      url: /components/mobile/introduction/
      weight: 1
    - name: Accordions
      url: /components/mobile/accordions/
    - name: Badges
      url: /components/mobile/badges/
    - name: Buttons
      url: /components/mobile/buttons/
    - name: Cards
      url: /components/mobile/cards/
    - name: Checkboxes
      url: /components/mobile/checkboxes/
    - name: Chips
      url: /components/mobile/chips/
    - name: Dialogs
      url: /components/mobile/dialogs/
    - name: Footers
      url: /components/mobile/footers/
    - name: Inputs
      url: /components/mobile/inputs/
    - name: Lists
      url: /components/mobile/lists/
    - name: Map Views
      url: /components/mobile/map-views/
    - name: Messages
      url: /components/mobile/messages/
    - name: Navbars
      url: /components/mobile/navbars/
    - name: Popovers
      url: /components/mobile/popovers/
    - name: Progress Indicators
      url: /components/mobile/progress-indicators/
    - name: Radio Buttons
      url: /components/mobile/radio-buttons/
    - name: Scrollbars
      url: /components/mobile/scrollbars/
    - name: Segmented Controls
      url: /components/mobile/segmented-controls/
    - name: Sliders
      url: /components/mobile/sliders/
    - name: Status Bars
      url: /components/mobile/status-bars/
    - name: Switches
      url: /components/mobile/switches/
    - name: Tabs
      url: /components/mobile/tabs/
    - name: Tables
      url: /components/mobile/tables/

  components_xr:
    - name: Introduction
      url: /components/xr/introduction/
      weight: 1
    - name: Backplates
      url: /components/xr/backplates/
    - name: Buttons
      url: /components/xr/buttons/
    - name: Cards
      url: /components/xr/cards/
    - name: Lists
      url: /components/xr/lists/
    - name: Modals
      url: /components/xr/modals/
    - name: Menus
      url: /components/xr/menus/
    - name: Sliders
      url: /components/xr/sliders/
    - name: Tooltips
      url: /components/xr/tooltips/

  resources:
    - name: "News & Articles"
      url: /news/
    - name: Community
      url: /community/
    - name: Contact
      url: /contact/

  community:
    - name: News & Articles
      url: /news/
      weight: 1
    - name: How to Contribute
      url: /community/contribute/
      weight: 2
    - name: Tiger Teams
      url: /community/tiger-teams/
      weight: 3
    - name: Contribution Process
      url: /community/contribution-process/
      weight: 4
    - name: Submission Guidelines
      url: /community/submission-guidelines/
      weight: 5
    - name: Modus Adoption
      url: /community/adoption/
      weight: 6
    - name: Contact Us
      url: /community/contact/
      weight: 7

module:
  mounts:
    - source: static
      target: static
    - source: assets/static/favicon.ico
      target: static/favicon.ico

    - source: assets/static/robots.txt
      target: static/robots.txt

    - source: node_modules/bootstrap/dist/js/bootstrap.bundle.min.js
      target: static/js/bootstrap.bundle.min.js

    - source: node_modules/bootstrap/dist/js/bootstrap.bundle.min.js.map
      target: static/js/bootstrap.bundle.min.js.map

    - source: node_modules/list.js/dist/list.min.js
      target: static/js/list.min.js

    - source: node_modules/list.js/dist/list.min.js.map
      target: static/js/list.min.js.map

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    codeFences: true
    style: monokai

# https://gohugo.io/getting-started/configuration/#configure-minify
minify:
  minifyOutput: true
  tdewolff:
    html:
      keepEndTags: false
      keepWhitespace: true
    js:
      keepVarNames: true
    xml:
      keepWhitespace: true
