baseurl: https://modus.trimble.com/
title: Trimble Modus Design System
languageCode: en-US
locale: en-US

enableInlineShortcodes: true
enableGitInfo: true

buildFuture: true

params:
  title: Trimble Modus Design System
  modusVersion: "1.0.0"
  modusLayoutVersion: "0.9.5"
  modusIconsVersion: "0.5.0"
  author: "Trimble"
  images:
    - https://modus.trimble.com/icon.png

publishdir: "./build/"

disableKinds: ["taxonomy", "taxonomyTerm", "RSS", "404"]

pygmentsUseClasses: true

outputs:
  home: ["HTML", "JSON"]

privacy:
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
  twitter:
    enableDNT: true
  youtube:
    privacyEnhanced: true

menu:
  main:
    - name: Start
      url: "/start/"
      weight: 1
    - name: Foundations
      url: "/foundations/"
      weight: 2
    - name: Elements
      url: "/elements/"
      weight: 3
    - Name: Community
      url: "/community/"
      weight: 4

  start:
    - name: Designers
      url: "/designers/"
      weight: 1
    - name: Developers
      url: "/developers/"
      weight: 2
    - name: Device Support
      url: "/device-support/"
      weight: 3
    - name: Status
      url: "/status/"
      weight: 4

  foundations:
    - name: Logo Usage
      url: /foundations/logo-usage/
      weight: 1
    - name: Writing Style
      url: /foundations/writing-style/
      weight: 2
    - name: Typography
      url: /foundations/typography/
      weight: 3
    - name: Color Palette
      url: /foundations/color-palette/
      weight: 4
    - name: Icon Definitions
      url: /foundations/icon-definitions/
      weight: 5
    - name: Accessibility
      url: /foundations/accessibility/
      weight: 6
    - name: Grid & Spacing
      url: /foundations/grid-and-spacing/
      weight: 7
    - name: Shadows & Depth
      url: /foundations/shadows-and-depth/
      weight: 8

  components:
    - name: Accordions
      url: /elements/accordions/
    - name: Alerts
      url: /elements/alerts/
    - name: Badges
      url: /elements/badges/
    - name: Breadcrumbs
      url: /elements/breadcrumbs/
    - name: Buttons
      url: /elements/buttons/
    - name: Cards
      url: /elements/cards/
    - name: Chips
      url: /elements/chips/
    - name: Checkboxes
      url: /elements/checkboxes/
    - name: Dialogs
      url: /elements/dialogs/
    - name: Dropdowns
      url: /elements/dropdowns/
    - name: Inputs
      url: /elements/inputs/
    - name: Lists
      url: /elements/lists/
    - name: Messages
      url: /elements/messages/
    - name: Pagination
      url: /elements/pagination/
    - name: Progress Bars
      url: /elements/progress-bars/
    - name: Radio Buttons
      url: /elements/radio-buttons/
    - name: Sliders
      url: /elements/sliders/
    - name: Spinners
      url: /elements/spinners/
    - name: Switches
      url: /elements/switches/
    - name: Tables
      url: /elements/tables/
    - name: Tabs
      url: /elements/tabs/
    - name: Toasts
      url: /elements/toasts/
    - name: Tooltips
      url: /elements/tooltips/

  resources:
    - name: "News & Articles"
      url: /news/
    - name: Community
      url: /community/
    - name: Contact
      url: /contact/

  community:
    - name: News & Articles
      url: /news/
      weight: 1
    - name: How to Contribute
      url: /community/contribute/
      weight: 2
    - name: Tiger Teams
      url: /community/tiger-teams/
      weight: 3
    - name: Contribution Process
      url: /community/contribution-process/
      weight: 4
    - name: Submission Guidelines
      url: /community/submission-guidelines/
      weight: 5
    - name: Contact Us
      url: /community/contact/
      weight: 6

module:
  mounts:
    - source: static
      target: static
    - source: assets/static/favicon.ico
      target: static/favicon.ico
    - source: assets/static/robots.txt
      target: static/robots.txt

markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    codeFences: true
    style: monokai

# https://gohugo.io/getting-started/configuration/#configure-minify
minify:
  minifyOutput: true
  tdewolff:
    html:
      keepEndTags: false
      keepWhitespace: true
    xml:
      keepWhitespace: true
