[build]
  command = "hugo --config config.yml,config-dev.yml"
  functions = "netlify/functions"
  publish = "build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests"
    Permissions-Policy = "microphone=()"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "0"

[[headers]]
  for = "favicon.*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, s-maxage=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=3600"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=1604800, immutable"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=1604800, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, immutable"
