[build]
  command = "hugo --config config.yml,config-dev.yml"
  functions = "netlify/functions"
  publish = "build"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests"
    Permissions-Policy = "microphone=()"
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, s-max-age=3600"

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Cache-Control = "public, max-age=1604800, immutable"

[[headers]]
  for = "/img/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, immutable"

[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, immutable"

[[plugins]]
package = "@netlify/plugin-lighthouse"

  # optional, fails build when a category is below a threshold
  [plugins.inputs.thresholds]
    performance = 0.5
    accessibility = 0.9
    best-practices = 0.8
    seo = 0.8
